### ISSUE TITLE
The squashfs does Illegal instruction on Intel Core2 Quad CPU

### ISSUE THREAD

**Issue by fransvanberckel** [ksovi/ovios#1]
Booting from the USB stick does not work. After the kernel and initrd load, I get a blinking line, that's all. I've tried everything the past two weeks. Is it the iso file? The usb stick? The computer architecture? Or just this computer that fails?

Dig deeper today. And investigated why it goes wrong.

$ uname -a

Linux deblnxsrv 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

$ ls -l OviOS_Linux_Rigel_20220729.iso

-rw-r--r-- 1 root root 727711744 Aug 21 07:45 OviOS_Linux_Rigel_20220729.iso

$ mkdir -p /mnt/iso /mnt/squashfs
$ mount ~/OviOS_Linux_Rigel_20220729.iso /mnt/iso

mount: /mnt/iso: WARNING: source write-protected, mounted read-only.

$ cp -a /mnt/iso/boot/x86_64/ovios.sfs ~/
$ umount /mnt/iso
$ ls -l ovios.sfs 

-rw-r--r-- 1 root root 699211776 Jul 29 16:17 ovios.sfs

$ mount -t squashfs -o loop ~/ovios.sfs /mnt/squashfs
$ df | grep loop

/dev/loop0         682880     682880          0 100% /mnt/squashfs

$ ls  /mnt/squashfs

bin boot dev etc home lib lib64 LICENSE media mnt opt proc root run sbin srv sys tmp usr var

$ chroot /mnt/squashfs/ /usr/bin/busybox ls

Illegal instruction

$ chroot /mnt/squashfs/ /usr/bin/setup

Illegal instruction

$ umount /mnt/squashfs

**Comment by fransvanberckel** [comment]
$ cat /proc/cpuinfo 

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping	: 11
microcode	: 0xb6
cpu MHz		: 1603.643
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4810.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

{snip} The other three

**Comment by fransvanberckel** [comment]
$ cat /proc/meminfo 
MemTotal:        4024784 kB
MemFree:          771428 kB
MemAvailable:    3609932 kB
Buffers:           86228 kB
Cached:          2901792 kB
SwapCached:            0 kB
Active:           121712 kB
Inactive:        2901848 kB
Active(anon):        508 kB
Inactive(anon):    35884 kB
Active(file):     121204 kB
Inactive(file):  2865964 kB
Unevictable:          16 kB
Mlocked:              16 kB
SwapTotal:      39063544 kB
SwapFree:       39063544 kB
Dirty:               224 kB
Writeback:             0 kB
AnonPages:         35588 kB
Mapped:            45772 kB
Shmem:               852 kB
KReclaimable:     110656 kB
Slab:             146164 kB
SReclaimable:     110656 kB
SUnreclaim:        35508 kB
KernelStack:        1936 kB
PageTables:         1524 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    41075936 kB
Committed_AS:     186484 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       26356 kB
VmallocChunk:          0 kB
Percpu:             2096 kB
HardwareCorrupted:     0 kB
AnonHugePages:      6144 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      101888 kB
DirectMap2M:     4091904 kB

**Comment by sskras** [comment]
@fransvanberckel commented [25 days ago](#issue-1345397784):

> Booting from the USB stick does not work. After the kernel and initrd load, I get a blinking line, that's all. 

One idea is to add some kernel option (via bootloader) that would increase verbosity of the boot process.

> I've tried everything the past two weeks. Is it the iso file? The usb stick? The computer architecture? Or just this computer that fails?

Another idea would be to run some other OS on that machine, install VirtualBox, KVM or Xen hypervisor on it, and then boot OviOS inside a VM. If it behaves the same, chances are that the kernel doesn't support the CPU/the northbridge.

(My 2 €c)

**Comment by ksovi** [comment]
Fixed in v5.0
